### ISSUE TITLE
v6 release checklist

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#649]
# TODO

- [x] YYP Maker runthru
- [x] Clean up repo project (duplicates, yys etc)
- [x] Update gamepad data
- Docs
	- [x] Do a sweep for old macros
	- [x] Do a sweep for broken links
	- [x] Checking Verbs
	- [x] 2D Checkers
	- [x] Advanced Checkers
	- [x] Further Verb Functions
	- [x] Binding Creators
	- [x] [Binding Access](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Binding-Access).md)
	- [x] [Binding Scanner](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Binding-Scan).md)
	- [x] [Icons](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Icons).md)
	- [x] [Cursor](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Cursor).md)
	- [x] [Cursor Control](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Cursor-Control).md)
	- [x] [Mouse Capture](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Mouse-Capture).md)
	- [x] [Accessibility](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Accessibility).md)
	- [x] [Exporting & Importing](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Exporting-and-Importing).md)
	- [x] [Virtual Buttons](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Virtual-Buttons).md)
	- [x] [Virtual Button Setup](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Virtual-Button-Setup).md)
	- [x] [Virtual Button Checkers](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Virtual-Button-Checkers).md)
	- [x] [Virtual Button Properties](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Virtual-Button-Properties).md)
	- [x] [Virtual Button History](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Virtual-Button-History).md)
	- [x] [Players](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Players).md)
	- [x] [Profiles](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Profiles).md)
	- [x] [Source Modes](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Source-Modes).md)
	- [x] [Sources](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Sources).md)
	- [x] [Vibration](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Vibration).md)
	- [x] [Color](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Color).md)
	- [x] [Gyro & Motion](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Gyro-And-Motion).md)
	- [x] [Trigger Effects](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Trigger-Effects).md)
	- [x] [Other](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Other).md)
	- [x] [Mouse (Direct)](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Mouse).md)
	- [x] [Gamepad (Direct)](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Gamepad).md)
	- [x] [Keyboard (Direct)](https://github.com/JujuAdams/Input/blob/docs/docs/6.0/Functions-(Keyboard).md)

**Comment by offalynne** [comment]
docs
- [ ] touch macro changes
- [ ] input_gamepad_mapping_contains
- [ ] input_verb_consume
- [ ] input_cursor_inverted...
- [ ] input_cursor_mouse...
- [ ] input_cursor_gyro...

**Comment by offalynne** [comment]
Docs
- [ ] Checking Verbs
- [ ] 2D Checkers
- [ ] Advanced Checkers
- [ ] Further Verb Functions
- [ ] Binding Creators
- [ ] Binding Access
- [ ] Binding Scanner
- [ ] Icons
- [ ] Cursor
- [ ] Cursor Control
- [ ] Mouse Capture
- [ ] Accessibility
- [ ] Exporting & Importing
- [ ] Virtual Buttons
- [ ] Virtual Button Methods
- [ ] Players
- [ ] Profiles
- [ ] Source Modes
- [ ] Sources
- [ ] Vibration
- [ ] Color
- [ ] Gyro & Motion
- [ ] Trigger Effects
- [ ] Other
- [ ] Mouse (Direct)
- [ ] Gamepad (Direct)
- [ ] Keyboard (Direct)
